<?php $isLoginPage=false;$pageTitle='Sales Leads - NovaTrack';require_once __DIR__.'/../../../views/layout/header.php';require_once __DIR__.'/_helpers.php'; ?>
<div class="topbar"><div class="topbar-inner"><div class="topbar-left"><span class="topbar-breadcrumb"><i class="bi bi-person-lines-fill"></i> Sales / Leads</span></div></div></div>
<main class="main-content"><section class="sales-shell">
<div class="sales-hero"><div><div class="sales-kicker"><i class="bi bi-person-plus"></i> Lead Intake</div><h1>Leads</h1><p>Catat calon client, kebutuhan legal, sumber lead, estimasi nilai, dan PIC follow-up.</p></div><div class="sales-actions"><a class="sales-btn secondary" href="<?= app_url('sales'); ?>"><i class="bi bi-speedometer2"></i> Overview</a></div></div>
<?php if (isset($_GET['created'])||isset($_GET['updated'])||isset($_GET['deleted'])): ?><div class="sales-alert"><i class="bi bi-check-circle"></i> Data lead berhasil diperbarui.</div><?php endif; ?>
<div class="sales-grid"><article class="sales-card span-5"><h2>Tambah Lead</h2><form class="sales-form" action="<?= app_url('sales/leads'); ?>" method="POST">
<div class="sales-field full"><label>Company / Client</label><input name="company_name" required></div><div class="sales-field"><label>PIC</label><input name="pic_name"></div><div class="sales-field"><label>Phone</label><input name="phone"></div><div class="sales-field"><label>Email</label><input name="email" type="email"></div><div class="sales-field"><label>Source</label><input name="source" placeholder="Referral, Website, Ads"></div><div class="sales-field"><label>Service</label><select name="service_id"><option value="">Pilih service</option><?php foreach($services as $s): ?><option value="<?= (int)$s['id']; ?>"><?= htmlspecialchars($s['name']); ?></option><?php endforeach; ?></select></div><div class="sales-field"><label>Need Category</label><input name="need_category" placeholder="Perizinan, Audit, Compliance"></div><div class="sales-field"><label>Estimated Value</label><input name="estimated_value" type="number" min="0" step="1000"></div><div class="sales-field"><label>Status</label><select name="status"><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="unqualified">Unqualified</option></select></div><div class="sales-field full"><label>Assigned</label><select name="assigned_user_id"><option value="">Unassigned</option><?php foreach($users as $u): ?><option value="<?= (int)$u['id']; ?>"><?= htmlspecialchars($u['full_name'] ?: $u['username']); ?></option><?php endforeach; ?></select></div><div class="sales-field full"><label>Notes</label><textarea name="notes"></textarea></div><div class="sales-field full"><button class="sales-btn" type="submit"><i class="bi bi-save"></i> Simpan Lead</button></div>
</form></article><article class="sales-card span-7"><h2>Daftar Leads</h2><div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Client</th><th>Contact</th><th>Service</th><th>Need</th><th>Value</th><th>Status</th><th>Assigned</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?= htmlspecialchars($row['company_name']); ?></strong><br><span><?= htmlspecialchars($row['source']); ?></span></td><td><?= htmlspecialchars($row['pic_name']); ?><br><span><?= htmlspecialchars($row['phone']); ?></span></td><td><?= htmlspecialchars($row['service_name'] ?? '-'); ?></td><td><?= htmlspecialchars($row['need_category']); ?></td><td><?= sales_money($row['estimated_value']); ?></td><td><span class="sales-pill"><?= sales_label($row['status']); ?></span></td><td><?= htmlspecialchars($row['assigned_name'] ?? '-'); ?></td><td class="sales-row-actions"><a class="sales-edit" href="<?= app_url('sales/leads/edit/'.(int)$row['id']); ?>"><i class="bi bi-pencil-square"></i></a><form action="<?= app_url('sales/leads/delete/'.(int)$row['id']); ?>" method="POST" onsubmit="return confirm('Hapus lead ini?');"><button class="sales-delete" type="submit"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; ?></tbody></table></div></article></div>
</section></main><footer class="app-footer"><span>&copy; <?= date('Y'); ?> NovaTrack Riksa</span><span class="app-footer-sep">|</span><span>Sales</span></footer><?php require __DIR__.'/styles.php'; ?></body></html>
